# Generated by Django 4.1.5 on 2023-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='회사명', max_length=255)),
                ('company_type', models.CharField(choices=[('telco', 'Telecommunication'), ('log', 'Logistics'), ('agr', 'Agriculture'), ('aero', 'Aerospace'), ('pharm', 'Pharmaceutical')], max_length=15)),
                ('founded', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compnay',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
